name: "CI/CD Pipeline"

on:
  push:
    branches:
      - master

concurrency:
  group: pipeline-smee-io-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-and-push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/master'
        id: buildx
        with:
          install: true
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Reset Multiarch Container
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build Image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            probablynot/smee.io:latest
            probablynot/smee.io:${{ github.sha }}
          platforms: |
            linux/amd64
            linux/arm64
